{% set name = "autocron" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autocron-{{ version }}.tar.gz
  sha256: 91815100863a5f7e3f8bce4d2d2ef6d259e95be909d335d2fade15b8b7d39993

build:
  entry_points:
    - autocron = autocron.admin:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8.0
    - setuptools
    - pip
  run:
    - python >=3.8.0

test:
  imports:
    - autocron
  commands:
    - pip check
    - autocron --help
  requires:
    - pip

about:
  home: https://github.com/kbr/autocron
  summary: Asynchronous background tasks for Python web-frameworks with no dependencies
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kbr
    - ReimarBauer
